.Dd July 11, 2026
.Dt XGAMEOFLIFE 6
.Sh NAME
.Nm xgameoflife
.Nd conway's game of life for X
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Op Ar file
.Sh DESCRIPTION
The game of life is a zero-player game created by John Conway.
Boards can be loaded from files in the native xg format or in
the run length encoded (RLE) pattern format, use - to read
from the standard input.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.El
.Sh CONTROLS
.Bl -bullet -compact -width indent
.It
move around pressing the middle click
.It
toggle cells pressing left click
.It
zoom in and out using the mouse wheel
.It
pause/resume the game with the space key
.It
advance to the next generation with the n key
.It
clear the board with the c key
.It
increase/decrease the simulation speed with the +/- keys
.It
save the current board with ctrl+s
.It
quit with the q or escape key
.El
.Sh SEE ALSO
.Xr X 7
.Xr gameoflife 6
.Xr xggen 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xgameoflife/issues
