.Dd August 9, 2022
.Dt XGAMEOFLIFE 6
.Sh NAME
.Nm xgameoflife
.Nd conway's game of life for X
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Op Fl l Ar file
.Sh DESCRIPTION
The game of life is a zero-player game created by John Conway.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.It Fl l
load saved board
.El
.Sh CONTROLS
.Bl -bullet -compact -width indent
.It
move around pressing the middle click
.It
toggle cells pressing left click
.It
zoom in and out using the mouse wheel
.It
pause/resume the game with the space key
.It
advance to the next generation with the n key
.It
save the current board with ctrl+s
.El
.Sh SEE ALSO
.Xr X 7
.Xr gameoflife 6
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xgameoflife/issues
