.TH XGGEN 1 "July 06, 2022"
.SH NAME
xggen \- generate xgameoflife compatible random board files.
.SH SYNOPSIS
\fBxggen\fP [ -c COLUMNS ] [ -r ROWS ] [ -p ALIVE_PROBABILITY ]
.SH OPTIONS
.TP
\fB\-c\fR
set the number of generated columns
.TP
\fB\-r\fR
set the number of generated rows
.TP
\fB\-r\fR
set the probability of generating an alive cell
.SH EXAMPLES
.TP
\fBgenerate a random 100x100 board\fR
xggen -c 100 -r 100 -p 0.2 | xgameoflife -l /dev/stdin
.SH AUTHOR
Written by alpheratz0.
.SH COPYRIGHT
Copyright \(co 2022 <alpheratz99@protonmail.com>
.br
License GPLv2.0: GNU GPL version 2.0 <https://gnu.org/licenses/old-licenses/gpl-2.0.en.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
.SH BUGS
https://github.com/alpheratz0/xgameoflife/issues
